# Generated by Django 4.2.4 on 2023-09-08 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_order_image_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
