# Generated by Django 4.2.4 on 2023-09-16 10:03

from django.db import migrations, models
import store.file_name_generator


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=store.file_name_generator.generate_filename),
        ),
    ]
